### ISSUE TITLE
Add More Error Handling

### ISSUE THREAD

**Issue by hnarasaki** [indeedeng/starfish#12]
Add error handling.

**Comment by danisyellis** [comment]
I agree that this project could use more error handling and messages to the user when things aren't working correctly!

Could you add any specifics to this issue? What functions should be checked for errors (and then those errors handled)? Have you seen any specific errors yourself when running Starfish that don't have error handling yet? The more specific the issue is, the more likely someone will have the time/bandwidth to take it on :-)

Thanks!

**Comment by danisyellis** [comment]
notes on one thing to add, quoted from an email:
"Because I ran it several times with blank output, I ended up rate limited. Errors should be caught, which I did by checking response.ok right before calling response.json."

**Comment by kevindigo** [comment]
I wish I had documented more clearly what errors I was seeing. The first can be replicated by having a mis-configuration that results in passing alternateIds (like email addresses) to GitHub as if they were githubIds. Starfish will just silently return no data. 

To fully test that this is fixed, you should probably disable passing your token, so that github will enforce tight rate limiting. Then run the app enough times in a row to trigger the rate limiting. At that point, with the current code you should start getting blank output again. But if it's fixed, you should see some kind of error message.

**Comment by kevindigo** [comment]
The code snippet above helped us get started, but appears to have been targeted for a different HTTP library. Fortunately, the node-fetch docs were pretty clear, so it wasn't hard to see what was needed.

**Comment by IngridGdesigns** [comment]
PR request for this Issue : [Handle error responses to HTTP requests](https://github.com/indeedeng/starfish/pull/34)
