### ISSUE TITLE
Update README.md CSV section

### ISSUE THREAD

**Issue by hnarasaki** [indeedeng/starfish#14]
Update the README.md CSV section. I did the setup and used VS Code as my IDE. I saw some weird things happen with the CSV, so would like more clarification on CSV setup.

**Comment by danisyellis** [comment]
From talking to you about this on Thursday, I think the plan is for you to
1. get to the point where you can create your own CSV and use it to run Starfish and get back correct info
2. document the things that were unclear in the README. (One of which is: if using a google sheet, put each category into its own column in the sheet so that a CSV has each category separated by a comma)
