### ISSUE TITLE
handle Github's API deprecation

### ISSUE THREAD

**Issue by danisyellis** [indeedeng/starfish#27]
we're getting emails that the way we're sending in our auth credentials (the Github API personal access tokens and OAuth app tokens) is deprecated and will stop working in July.

Here is an example of the GitHub email:

> On February 7th, 2020 at 14:35 (UTC) your application (starfish) used its `client_id` and `client_secret` (with the User-Agent node-fetch/1.0 (+https://github.com/bitinn/node-fetch)) as part of a set of query parameters to access an endpoint through the GitHub API:
https://api.github.com/user/{usernumberhere}/events

> Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.

> Depending on your API usage, we'll be sending you this email reminder at most once every 3 days.
> Just one URL that was accessed with a User-Agent combination will be listed in the email reminder, not all.
Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

> Thanks,
> The GitHub Team

And here are some notes from an email with Kevin about how to handle this: 
when I was still blocked by rate limiting, I was able to work around that by passing the token that I configured in my .env file. Before calling fetch, I constructed a headers with Basic authentication[1]. I'm not sure why passing it as a URL parameter didn't work.  
[1]   
  let headers = {
    Authorization:
      "Basic " +
      Buffer.from(githubClientID + ":" + githubClientSecret).toString("base64")
  };
...
    fetch(url, {
      method: "GET",
      headers: headers
      //credentials: 'user:passwd'
    })

**Comment by NckHmml** [comment]
Had a quick look at this while trying to get the code to run.
But it looks like the combination of personal access token + basic auth won't be deprecated. (https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens)
Or does the personal access token have any disadvantages?

Got it to work so I can make a PR if you like, but I probably should update the readme too then.

**Comment by danisyellis** [comment]
Hi @NckHmml thanks for working on this!
I took a quick look at the code in your fork and it looks good.
Also, you're right, we should switch to using a personal access token instead of OAuth app credentials. If you'd like to change the README that would be great! If not, you can just submit the code as a PR and I'll fix the README.

**Comment by jeffwilcox** [comment]
Just FYI - 
I adapted some of this code to work on a rolling basis using a modern GitHub App and that authentication approach... we have rate limiting challenges trying to discover all the contributions people have made, and by moving to the GitHub App, we get a lot more API tokens to play with.

Unfortunately it's a frakenmess of code since our existing infrastructure is pretty complex, but I'm happy to share what I can if people think there would be value there.

I'm also using octokit rest.js (https://github.com/octokit/rest.js/), as we maintain an e-tag cache of all these responses... we collect the data on our users all day long now, and so with the e-tag, if there's been no new change in contributions, it doesn't cost us an API call, and speeds along the process.
